### ISSUE TITLE
域名过期了？

### ISSUE THREAD

**Issue by hack2012** [lijiejie/eyes.sh#12]
eyss.sh域名访问不了兄弟

**Comment by lijiejie** [comment]
感谢，已经恢复了。  之前自己域名上了cloudflare，NS记录的域名被代理了

**Comment by Gs52jrfnxnPXBGAW** [comment]
目前还是无法访问

**Comment by lijiejie** [comment]
> 目前还是无法访问

已经恢复了服务。 之前因为更新代码，出了一点问题。DNS服务没启动
