### ISSUE TITLE
dnslog 无任何请求记录

### ISSUE THREAD

**Issue by Superhero-zero** [lijiejie/eyes.sh#13]
在测试dnlog日志时，并无任何请求数据
![image](https://github.com/lijiejie/eyes.sh/assets/66772820/e90f31dc-140e-4bf3-abd4-a4925a3b0026)

**Comment by Superhero-zero** [comment]
> 在测试dnlog日志时，并无任何请求数据 ![image](https://private-user-images.githubusercontent.com/66772820/298375562-e90f31dc-140e-4bf3-abd4-a4925a3b0026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzI4NzYsIm5iZiI6MTcwNTgzMjU3NiwicGF0aCI6Ii82Njc3MjgyMC8yOTgzNzU1NjItZTkwZjMxZGMtMTQwZS00YmYzLWFiZDQtYTQ5MjVhM2IwMDI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNTdlMGJlYmM5ZDBjNzIxNjkyMDM0OWQ1YjUwNmZjOTdlODdmZDcxYTQ1OWQ4MzdkMjk3MDVkOWQ3Y2I3ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AMKDGfVt3tVzPyIXPunX2hhhmhy6_nyKJbwm0Oxt1io)

![image](https://github.com/lijiejie/eyes.sh/assets/66772820/3109634c-7fed-4af4-81ae-8d61bf6f088f)

**Comment by Xiaosesh** [comment]
老哥，解决了嘛，我也遇到了这个问题

**Comment by lijiejie** [comment]
服务已经恢复  ：）
