### ISSUE TITLE
等一个好心人做Docker镜像

### ISSUE THREAD

**Issue by coffeehb** [lijiejie/eyes.sh#3]
等一个docker一键部署方案

**Comment by lijiejie** [comment]
已经merge了其他同学写的docker file，可以试试看

**Comment by coffeehb** [comment]
部署起来了，测了一下应该可以的。
记录一下踩过的几个坑。
1. .env和docker_nginx.conf文件是需要自己修改的
2. 没有备案的话，直接修改nginx配置文件的server name修改变量为自己vps ip，使用IP访问管理端
3. IP访问出现403，csrf检验失败，去dnslog模块下setting.py文件删除Django的CSRF检验模块

**Comment by coffeehb** [comment]
经过周末试用，DNS可以正常记录。因为没有备案网站无法打开所以Weblog无法记录。sad~
