### ISSUE TITLE
weblog功能不生效

### ISSUE THREAD

**Issue by okoling** [lijiejie/eyes.sh#4]
使用eyes.sh和自己搭建的都一样
发送post
```
curl  6ux5rl5z.eyes.sh -X POST -d "123123"
curl: (6) Could not resolve host: 6ux5rl5z.eyes.sh
```
只有dnslog有记录，weblog没有显示

**Comment by lijiejie** [comment]
感谢反馈，是nginx配置的问题，因为这边把默认站点启用了。 但是没有改servername
你可以再试试

**Comment by lijiejie** [comment]
https://github.com/lijiejie/eyes.sh/blob/master/dnslog_nginx.conf

**Comment by okoling** [comment]
解决了，另外IP位置好像不太准确。。可以做成本地纯真识别也不错

**Comment by lijiejie** [comment]
> 解决了，另外IP位置好像不太准确。。可以做成本地纯真识别也不错

看起来有不准的问题， 稍后会考虑改进一下。 换接口或者本地查找

**Comment by coffeehb** [comment]
好像不太对
server_name localhost $ADMIN_DOMAI;
应该是这个？
server_name localhost $ADMIN_DOMAIN;

**Comment by lijiejie** [comment]
上周review看了一下配置就merge了，没有实际去部署。 应该是这个问题，刚fix了

**Comment by coffeehb** [comment]
我是IP直接访问的后台，我是域名直接解析到腾讯云IP，因为没有备案被拦截了，无法测试是否有效。没有备案的网站，无法使用Weblog了吗？

**Comment by Lengso** [comment]
dnslog_nginx.conf ：server_name localhost $ADMIN_DOMAIN;  得手动更改
加上域名加类似：eyes.sh www.eyes.sh *.eyes.sh; 这三个才能使用weblog功能
